INFO:root:Wed Aug 26 10:24:49 2020 | Data from Google Sheet retrieved at Wed Aug 26 10:24:49 2020
INFO:root:Wed Aug 26 10:24:49 2020 | cpu times: OrderedDict([('user', 238.05), ('nice', 32.8), ('system', 66.1), ('idle', 154804.05), ('iowait', 46.76), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.78), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 291643392), ('percent', 71.6), ('used', 573702144), ('free', 72335360), ('active', 656404480), ('inactive', 159498240), ('buffers', 80867328), ('cached', 299253760), ('shared', 786432), ('slab', 97873920)])
INFO:root:Wed Aug 26 10:24:49 2020 | Beginning processing at Wed Aug 26 10:24:49 2020, running 2 queries
INFO:root:Wed Aug 26 10:24:49 2020 | cpu times: OrderedDict([('user', 238.05), ('nice', 32.8), ('system', 66.1), ('idle', 154804.05), ('iowait', 46.76), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.78), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 291643392), ('percent', 71.6), ('used', 573702144), ('free', 72335360), ('active', 656699392), ('inactive', 159498240), ('buffers', 80867328), ('cached', 299253760), ('shared', 786432), ('slab', 97873920)])
INFO:root:Wed Aug 26 10:25:05 2020 | Error | query returned 0 results
INFO:root:Wed Aug 26 10:25:22 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 10:25:22 2020,
INFO:root:Wed Aug 26 10:25:22 2020 | Processing completed in 32.75 seconds
INFO:root:Wed Aug 26 10:25:22 2020 | cpu times: OrderedDict([('user', 240.91), ('nice', 32.8), ('system', 66.3), ('idle', 154833.43), ('iowait', 46.96), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.79), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 263630848), ('percent', 74.3), ('used', 602673152), ('free', 66727936), ('active', 672952320), ('inactive', 150462464), ('buffers', 73302016), ('cached', 283455488), ('shared', 786432), ('slab', 95674368)])
INFO:root:Wed Aug 26 10:26:22 2020 | cpu times: OrderedDict([('user', 241.23), ('nice', 32.8), ('system', 66.34), ('idle', 154892.98), ('iowait', 46.98), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.8), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 273342464), ('percent', 73.4), ('used', 592969728), ('free', 78422016), ('active', 663633920), ('inactive', 148676608), ('buffers', 72814592), ('cached', 281952256), ('shared', 786432), ('slab', 95617024)])
INFO:root:Wed Aug 26 10:27:22 2020 | cpu times: OrderedDict([('user', 241.27), ('nice', 32.8), ('system', 66.36), ('idle', 154952.84), ('iowait', 46.99), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.8), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 272850944), ('percent', 73.4), ('used', 593461248), ('free', 77905920), ('active', 664051712), ('inactive', 148676608), ('buffers', 72830976), ('cached', 281960448), ('shared', 786432), ('slab', 95617024)])
INFO:root:Wed Aug 26 10:28:22 2020 | cpu times: OrderedDict([('user', 241.32), ('nice', 32.8), ('system', 66.39), ('idle', 155012.7), ('iowait', 46.99), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.81), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 271716352), ('percent', 73.5), ('used', 594595840), ('free', 76615680), ('active', 665489408), ('inactive', 148811776), ('buffers', 72843264), ('cached', 282103808), ('shared', 786432), ('slab', 95617024)])
INFO:root:Wed Aug 26 10:29:22 2020 | cpu times: OrderedDict([('user', 242.8), ('nice', 32.8), ('system', 66.59), ('idle', 155070.89), ('iowait', 47.02), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.82), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 259244032), ('percent', 74.7), ('used', 608354304), ('free', 80424960), ('active', 670277632), ('inactive', 142934016), ('buffers', 67420160), ('cached', 269959168), ('shared', 786432), ('slab', 92643328)])
INFO:root:Wed Aug 26 10:30:22 2020 | cpu times: OrderedDict([('user', 245.33), ('nice', 32.8), ('system', 66.7), ('idle', 155128.18), ('iowait', 47.04), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.85), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 260870144), ('percent', 74.6), ('used', 606728192), ('free', 80920576), ('active', 670072832), ('inactive', 142327808), ('buffers', 67588096), ('cached', 270921728), ('shared', 786432), ('slab', 92643328)])
INFO:root:Wed Aug 26 10:31:02 2020 | Data from Google Sheet retrieved at Wed Aug 26 10:31:02 2020
INFO:root:Wed Aug 26 10:31:02 2020 | cpu times: OrderedDict([('user', 246.87), ('nice', 32.8), ('system', 66.92), ('idle', 155165.97), ('iowait', 47.05), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.86), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 274169856), ('percent', 73.3), ('used', 593428480), ('free', 94138368), ('active', 670216192), ('inactive', 128999424), ('buffers', 67608576), ('cached', 270983168), ('shared', 786432), ('slab', 92618752)])
INFO:root:Wed Aug 26 10:31:02 2020 | Beginning processing at Wed Aug 26 10:31:02 2020, running 2 queries
INFO:root:Wed Aug 26 10:31:02 2020 | cpu times: OrderedDict([('user', 246.87), ('nice', 32.8), ('system', 66.92), ('idle', 155165.97), ('iowait', 47.05), ('irq', 0.0), ('softirq', 1.25), ('steal', 20.86), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 274944000), ('percent', 73.2), ('used', 592654336), ('free', 94912512), ('active', 669478912), ('inactive', 128999424), ('buffers', 67608576), ('cached', 270983168), ('shared', 786432), ('slab', 92618752)])
INFO:root:Wed Aug 26 10:31:17 2020 | Error | query returned 0 results
INFO:root:Wed Aug 26 10:31:35 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 10:31:35 2020,
INFO:root:Wed Aug 26 10:31:36 2020 | Processing completed in 34.02 seconds
INFO:root:Wed Aug 26 10:31:36 2020 | cpu times: OrderedDict([('user', 248.7), ('nice', 32.8), ('system', 67.06), ('idle', 155197.92), ('iowait', 47.05), ('irq', 0.0), ('softirq', 1.26), ('steal', 20.87), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 257163264), ('percent', 74.9), ('used', 610435072), ('free', 77123584), ('active', 689487872), ('inactive', 126640128), ('buffers', 67616768), ('cached', 270983168), ('shared', 786432), ('slab', 92692480)])
INFO:root:Wed Aug 26 10:32:36 2020 | cpu times: OrderedDict([('user', 251.33), ('nice', 32.8), ('system', 67.16), ('idle', 155255.15), ('iowait', 47.06), ('irq', 0.0), ('softirq', 1.26), ('steal', 20.87), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 251244544), ('percent', 75.5), ('used', 616353792), ('free', 71188480), ('active', 696475648), ('inactive', 126640128), ('buffers', 67633152), ('cached', 270983168), ('shared', 786432), ('slab', 92692480)])
INFO:root:Wed Aug 26 10:33:36 2020 | cpu times: OrderedDict([('user', 252.87), ('nice', 32.8), ('system', 67.25), ('idle', 155313.44), ('iowait', 47.06), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.88), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 235077632), ('percent', 77.1), ('used', 632786944), ('free', 76496896), ('active', 703303680), ('inactive', 115187712), ('buffers', 61239296), ('cached', 255635456), ('shared', 786432), ('slab', 91758592)])
INFO:root:Wed Aug 26 10:34:36 2020 | cpu times: OrderedDict([('user', 253.21), ('nice', 32.8), ('system', 67.42), ('idle', 155372.8), ('iowait', 47.07), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.9), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 233316352), ('percent', 77.3), ('used', 634548224), ('free', 74452992), ('active', 704606208), ('inactive', 115036160), ('buffers', 61472768), ('cached', 255684608), ('shared', 786432), ('slab', 91758592)])
INFO:root:Wed Aug 26 10:35:36 2020 | cpu times: OrderedDict([('user', 253.56), ('nice', 32.8), ('system', 67.62), ('idle', 155432.12), ('iowait', 47.11), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.91), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 218988544), ('percent', 78.7), ('used', 648806400), ('free', 75661312), ('active', 704200704), ('inactive', 114372608), ('buffers', 56856576), ('cached', 244834304), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:36:36 2020 | cpu times: OrderedDict([('user', 253.87), ('nice', 32.8), ('system', 67.69), ('idle', 155491.67), ('iowait', 47.11), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.92), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 218451968), ('percent', 78.7), ('used', 649342976), ('free', 74858496), ('active', 705134592), ('inactive', 114397184), ('buffers', 56877056), ('cached', 245080064), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:37:36 2020 | cpu times: OrderedDict([('user', 253.89), ('nice', 32.8), ('system', 67.7), ('idle', 155551.52), ('iowait', 47.12), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.93), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 217321472), ('percent', 78.8), ('used', 650473472), ('free', 73568256), ('active', 706613248), ('inactive', 114397184), ('buffers', 56885248), ('cached', 245231616), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:38:36 2020 | cpu times: OrderedDict([('user', 253.92), ('nice', 32.8), ('system', 67.71), ('idle', 155611.43), ('iowait', 47.12), ('irq', 0.0), ('softirq', 1.27), ('steal', 20.93), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 217591808), ('percent', 78.8), ('used', 650199040), ('free', 73826304), ('active', 705826816), ('inactive', 114397184), ('buffers', 56901632), ('cached', 245231616), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:39:36 2020 | cpu times: OrderedDict([('user', 255.01), ('nice', 32.8), ('system', 67.86), ('idle', 155670.14), ('iowait', 47.12), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.94), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 262582272), ('percent', 74.4), ('used', 605212672), ('free', 118333440), ('active', 665399296), ('inactive', 111079424), ('buffers', 56918016), ('cached', 245694464), ('shared', 786432), ('slab', 91463680)])
INFO:root:Wed Aug 26 10:40:36 2020 | cpu times: OrderedDict([('user', 255.05), ('nice', 32.8), ('system', 67.88), ('idle', 155730.03), ('iowait', 47.13), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.95), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 262598656), ('percent', 74.4), ('used', 605196288), ('free', 118333440), ('active', 665321472), ('inactive', 111083520), ('buffers', 56930304), ('cached', 245698560), ('shared', 786432), ('slab', 91463680)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 10:41:37 2020 | Data from Google Sheet retrieved at Wed Aug 26 10:41:37 2020
INFO:root:Wed Aug 26 10:41:37 2020 | cpu times: OrderedDict([('user', 255.18), ('nice', 32.8), ('system', 67.92), ('idle', 155790.79), ('iowait', 47.13), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.96), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 247504896), ('percent', 75.9), ('used', 620290048), ('free', 103108608), ('active', 681299968), ('inactive', 111087616), ('buffers', 56946688), ('cached', 245813248), ('shared', 786432), ('slab', 91463680)])
INFO:root:Wed Aug 26 10:41:37 2020 | Beginning processing at Wed Aug 26 10:41:37 2020, running 2 queries
INFO:root:Wed Aug 26 10:41:37 2020 | cpu times: OrderedDict([('user', 255.19), ('nice', 32.8), ('system', 67.92), ('idle', 155790.79), ('iowait', 47.13), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.96), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 246988800), ('percent', 75.9), ('used', 620806144), ('free', 102592512), ('active', 681668608), ('inactive', 111087616), ('buffers', 56946688), ('cached', 245813248), ('shared', 786432), ('slab', 91463680)])
INFO:root:Wed Aug 26 10:41:53 2020 | Error | query returned 0 results
INFO:root:Wed Aug 26 10:42:08 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 10:42:08 2020,
INFO:root:Wed Aug 26 10:42:09 2020 | Processing completed in 31.52 seconds
INFO:root:Wed Aug 26 10:42:09 2020 | cpu times: OrderedDict([('user', 255.47), ('nice', 32.8), ('system', 67.94), ('idle', 155821.95), ('iowait', 47.14), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.96), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 240488448), ('percent', 76.6), ('used', 627306496), ('free', 96059392), ('active', 687886336), ('inactive', 111099904), ('buffers', 56963072), ('cached', 245829632), ('shared', 786432), ('slab', 91463680)])
INFO:root:Wed Aug 26 10:43:09 2020 | cpu times: OrderedDict([('user', 255.48), ('nice', 32.8), ('system', 67.94), ('idle', 155881.86), ('iowait', 47.14), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.97), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 238321664), ('percent', 76.8), ('used', 629469184), ('free', 93880320), ('active', 688885760), ('inactive', 111099904), ('buffers', 56979456), ('cached', 245829632), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:44:09 2020 | cpu times: OrderedDict([('user', 255.5), ('nice', 32.8), ('system', 67.96), ('idle', 155941.76), ('iowait', 47.14), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.98), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 239964160), ('percent', 76.6), ('used', 627830784), ('free', 95510528), ('active', 687353856), ('inactive', 111071232), ('buffers', 56987648), ('cached', 245829632), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:45:09 2020 | cpu times: OrderedDict([('user', 255.52), ('nice', 32.8), ('system', 67.98), ('idle', 156001.63), ('iowait', 47.15), ('irq', 0.0), ('softirq', 1.28), ('steal', 20.98), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241053696), ('percent', 76.5), ('used', 626733056), ('free', 96591872), ('active', 686776320), ('inactive', 111058944), ('buffers', 57004032), ('cached', 245829632), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:46:09 2020 | cpu times: OrderedDict([('user', 255.55), ('nice', 32.8), ('system', 67.98), ('idle', 156061.49), ('iowait', 47.15), ('irq', 0.0), ('softirq', 1.29), ('steal', 20.98), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241618944), ('percent', 76.5), ('used', 626176000), ('free', 97140736), ('active', 686075904), ('inactive', 111058944), ('buffers', 57012224), ('cached', 245829632), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:47:09 2020 | cpu times: OrderedDict([('user', 255.56), ('nice', 32.8), ('system', 67.99), ('idle', 156121.42), ('iowait', 47.16), ('irq', 0.0), ('softirq', 1.29), ('steal', 20.99), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241729536), ('percent', 76.4), ('used', 626057216), ('free', 97107968), ('active', 686379008), ('inactive', 111194112), ('buffers', 57028608), ('cached', 245964800), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:48:09 2020 | cpu times: OrderedDict([('user', 255.58), ('nice', 32.8), ('system', 68.01), ('idle', 156181.32), ('iowait', 47.16), ('irq', 0.0), ('softirq', 1.29), ('steal', 20.99), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241745920), ('percent', 76.4), ('used', 626049024), ('free', 97107968), ('active', 686440448), ('inactive', 111194112), ('buffers', 57036800), ('cached', 245964800), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:49:09 2020 | cpu times: OrderedDict([('user', 255.58), ('nice', 32.8), ('system', 68.02), ('idle', 156241.23), ('iowait', 47.17), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.0), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241238016), ('percent', 76.5), ('used', 626548736), ('free', 96591872), ('active', 686747648), ('inactive', 111194112), ('buffers', 57053184), ('cached', 245964800), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:50:09 2020 | cpu times: OrderedDict([('user', 255.59), ('nice', 32.8), ('system', 68.03), ('idle', 156301.15), ('iowait', 47.17), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.0), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 241057792), ('percent', 76.5), ('used', 626737152), ('free', 96333824), ('active', 687116288), ('inactive', 111194112), ('buffers', 57061376), ('cached', 246026240), ('shared', 786432), ('slab', 91496448)])
INFO:root:Wed Aug 26 10:51:09 2020 | cpu times: OrderedDict([('user', 255.61), ('nice', 32.8), ('system', 68.03), ('idle', 156361.08), ('iowait', 47.18), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.01), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 240807936), ('percent', 76.5), ('used', 626978816), ('free', 96075776), ('active', 687398912), ('inactive', 111194112), ('buffers', 57077760), ('cached', 246026240), ('shared', 786432), ('slab', 91496448)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 10:52:10 2020 | Data from Google Sheet retrieved at Wed Aug 26 10:52:10 2020
INFO:root:Wed Aug 26 10:52:10 2020 | cpu times: OrderedDict([('user', 257.23), ('nice', 32.8), ('system', 68.49), ('idle', 156419.68), ('iowait', 47.49), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.02), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 219791360), ('percent', 78.6), ('used', 647876608), ('free', 74350592), ('active', 711667712), ('inactive', 105717760), ('buffers', 56164352), ('cached', 247767040), ('shared', 811008), ('slab', 91664384)])
INFO:root:Wed Aug 26 10:52:10 2020 | Beginning processing at Wed Aug 26 10:52:10 2020, running 1 queries
INFO:root:Wed Aug 26 10:52:10 2020 | cpu times: OrderedDict([('user', 257.23), ('nice', 32.8), ('system', 68.49), ('idle', 156419.68), ('iowait', 47.49), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.02), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 219791360), ('percent', 78.6), ('used', 647876608), ('free', 74350592), ('active', 711888896), ('inactive', 105717760), ('buffers', 56164352), ('cached', 247767040), ('shared', 811008), ('slab', 91664384)])
INFO:root:Wed Aug 26 10:52:27 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 10:52:27 2020,
INFO:root:Wed Aug 26 10:52:27 2020 | Processing completed in 16.84 seconds
INFO:root:Wed Aug 26 10:52:27 2020 | cpu times: OrderedDict([('user', 257.37), ('nice', 32.8), ('system', 68.51), ('idle', 156436.32), ('iowait', 47.49), ('irq', 0.0), ('softirq', 1.29), ('steal', 21.02), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 218349568), ('percent', 78.7), ('used', 649318400), ('free', 72835072), ('active', 714264576), ('inactive', 105717760), ('buffers', 56172544), ('cached', 247832576), ('shared', 811008), ('slab', 91631616)])
INFO:root:Wed Aug 26 10:53:27 2020 | cpu times: OrderedDict([('user', 257.49), ('nice', 32.8), ('system', 68.55), ('idle', 156496.08), ('iowait', 47.5), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.03), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 216035328), ('percent', 78.9), ('used', 651632640), ('free', 70393856), ('active', 716398592), ('inactive', 105648128), ('buffers', 56180736), ('cached', 247951360), ('shared', 811008), ('slab', 91680768)])
INFO:root:Wed Aug 26 10:54:27 2020 | cpu times: OrderedDict([('user', 257.52), ('nice', 32.8), ('system', 68.57), ('idle', 156555.95), ('iowait', 47.5), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.04), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 215552000), ('percent', 79.0), ('used', 652115968), ('free', 69795840), ('active', 716664832), ('inactive', 105648128), ('buffers', 56197120), ('cached', 248049664), ('shared', 811008), ('slab', 91721728)])
INFO:root:Wed Aug 26 10:55:27 2020 | cpu times: OrderedDict([('user', 258.54), ('nice', 32.8), ('system', 68.88), ('idle', 156614.54), ('iowait', 47.51), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.05), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 210825216), ('percent', 79.5), ('used', 656859136), ('free', 95825920), ('active', 701636608), ('inactive', 92024832), ('buffers', 50454528), ('cached', 223019008), ('shared', 827392), ('slab', 91668480)])
INFO:root:Wed Aug 26 10:56:27 2020 | cpu times: OrderedDict([('user', 259.15), ('nice', 32.8), ('system', 69.07), ('idle', 156673.62), ('iowait', 47.53), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.05), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 208465920), ('percent', 79.7), ('used', 659210240), ('free', 93089792), ('active', 704520192), ('inactive', 91922432), ('buffers', 50470912), ('cached', 223387648), ('shared', 835584), ('slab', 91848704)])
INFO:root:Wed Aug 26 10:57:27 2020 | cpu times: OrderedDict([('user', 259.2), ('nice', 32.8), ('system', 69.08), ('idle', 156733.52), ('iowait', 47.53), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.06), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 207147008), ('percent', 79.8), ('used', 660529152), ('free', 91717632), ('active', 705540096), ('inactive', 91922432), ('buffers', 50479104), ('cached', 223432704), ('shared', 835584), ('slab', 91848704)])
INFO:root:Wed Aug 26 10:58:27 2020 | cpu times: OrderedDict([('user', 259.26), ('nice', 32.8), ('system', 69.1), ('idle', 156793.37), ('iowait', 47.53), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.07), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 204967936), ('percent', 80.0), ('used', 662708224), ('free', 89522176), ('active', 706727936), ('inactive', 91922432), ('buffers', 50495488), ('cached', 223432704), ('shared', 835584), ('slab', 91897856)])
INFO:root:Wed Aug 26 10:59:27 2020 | cpu times: OrderedDict([('user', 259.73), ('nice', 32.8), ('system', 69.21), ('idle', 156852.69), ('iowait', 47.54), ('irq', 0.0), ('softirq', 1.3), ('steal', 21.07), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 204275712), ('percent', 80.1), ('used', 663453696), ('free', 88694784), ('active', 707158016), ('inactive', 92000256), ('buffers', 50503680), ('cached', 223506432), ('shared', 843776), ('slab', 92135424)])
INFO:root:Wed Aug 26 11:00:27 2020 | cpu times: OrderedDict([('user', 260.49), ('nice', 32.8), ('system', 69.42), ('idle', 156911.58), ('iowait', 47.55), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.25), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 202469376), ('percent', 80.3), ('used', 665243648), ('free', 86781952), ('active', 708210688), ('inactive', 91975680), ('buffers', 50520064), ('cached', 223612928), ('shared', 851968), ('slab', 92332032)])
INFO:root:Wed Aug 26 11:01:27 2020 | cpu times: OrderedDict([('user', 260.52), ('nice', 32.8), ('system', 69.43), ('idle', 156971.43), ('iowait', 47.55), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.26), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 201969664), ('percent', 80.3), ('used', 665743360), ('free', 86265856), ('active', 709210112), ('inactive', 91979776), ('buffers', 50536448), ('cached', 223612928), ('shared', 851968), ('slab', 92332032)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 11:02:28 2020 | Data from Google Sheet retrieved at Wed Aug 26 11:02:28 2020
INFO:root:Wed Aug 26 11:02:28 2020 | cpu times: OrderedDict([('user', 260.67), ('nice', 32.8), ('system', 69.45), ('idle', 157032.26), ('iowait', 47.56), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.26), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 187789312), ('percent', 81.7), ('used', 679923712), ('free', 72073216), ('active', 723918848), ('inactive', 91975680), ('buffers', 50552832), ('cached', 223608832), ('shared', 851968), ('slab', 92332032)])
INFO:root:Wed Aug 26 11:02:28 2020 | Beginning processing at Wed Aug 26 11:02:28 2020, running 1 queries
INFO:root:Wed Aug 26 11:02:28 2020 | cpu times: OrderedDict([('user', 260.67), ('nice', 32.8), ('system', 69.45), ('idle', 157032.26), ('iowait', 47.56), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.26), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 187539456), ('percent', 81.7), ('used', 680173568), ('free', 71815168), ('active', 724152320), ('inactive', 91975680), ('buffers', 50552832), ('cached', 223617024), ('shared', 851968), ('slab', 92332032)])
INFO:root:Wed Aug 26 11:02:49 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 11:02:49 2020,
INFO:root:Wed Aug 26 11:02:50 2020 | Processing completed in 21.18 seconds
INFO:root:Wed Aug 26 11:02:50 2020 | cpu times: OrderedDict([('user', 260.81), ('nice', 32.8), ('system', 69.47), ('idle', 157053.25), ('iowait', 47.56), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.26), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 187564032), ('percent', 81.7), ('used', 680148992), ('free', 71839744), ('active', 724553728), ('inactive', 91975680), ('buffers', 50552832), ('cached', 223617024), ('shared', 851968), ('slab', 92307456)])
INFO:root:Wed Aug 26 11:03:50 2020 | cpu times: OrderedDict([('user', 260.84), ('nice', 32.8), ('system', 69.49), ('idle', 157113.17), ('iowait', 47.57), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.27), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 187064320), ('percent', 81.8), ('used', 680648704), ('free', 71323648), ('active', 723832832), ('inactive', 91975680), ('buffers', 50569216), ('cached', 223617024), ('shared', 851968), ('slab', 92307456)])
INFO:root:Wed Aug 26 11:04:50 2020 | cpu times: OrderedDict([('user', 260.87), ('nice', 32.8), ('system', 69.5), ('idle', 157173.02), ('iowait', 47.57), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.27), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 186605568), ('percent', 81.8), ('used', 681107456), ('free', 70807552), ('active', 724156416), ('inactive', 91975680), ('buffers', 50577408), ('cached', 223666176), ('shared', 851968), ('slab', 92307456)])
INFO:root:Wed Aug 26 11:05:50 2020 | cpu times: OrderedDict([('user', 260.89), ('nice', 32.8), ('system', 69.52), ('idle', 157232.92), ('iowait', 47.58), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.28), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 186384384), ('percent', 81.8), ('used', 681328640), ('free', 70533120), ('active', 724512768), ('inactive', 91971584), ('buffers', 50593792), ('cached', 223703040), ('shared', 851968), ('slab', 92323840)])
INFO:root:Wed Aug 26 11:06:50 2020 | cpu times: OrderedDict([('user', 260.92), ('nice', 32.8), ('system', 69.52), ('idle', 157292.79), ('iowait', 47.58), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.28), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 186146816), ('percent', 81.9), ('used', 681566208), ('free', 70275072), ('active', 724803584), ('inactive', 91975680), ('buffers', 50610176), ('cached', 223707136), ('shared', 851968), ('slab', 92323840)])
INFO:root:Wed Aug 26 11:07:50 2020 | cpu times: OrderedDict([('user', 260.95), ('nice', 32.8), ('system', 69.52), ('idle', 157352.65), ('iowait', 47.59), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.29), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 185868288), ('percent', 81.9), ('used', 681844736), ('free', 69984256), ('active', 725131264), ('inactive', 91979776), ('buffers', 50618368), ('cached', 223711232), ('shared', 851968), ('slab', 92323840)])
INFO:root:Wed Aug 26 11:08:50 2020 | cpu times: OrderedDict([('user', 260.97), ('nice', 32.8), ('system', 69.53), ('idle', 157412.51), ('iowait', 47.59), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.29), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 185286656), ('percent', 81.9), ('used', 682426368), ('free', 69386240), ('active', 726298624), ('inactive', 91979776), ('buffers', 50634752), ('cached', 223711232), ('shared', 851968), ('slab', 92323840)])
INFO:root:Wed Aug 26 11:09:50 2020 | cpu times: OrderedDict([('user', 260.99), ('nice', 32.8), ('system', 69.55), ('idle', 157472.37), ('iowait', 47.6), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.3), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 184041472), ('percent', 82.1), ('used', 683671552), ('free', 68096000), ('active', 726470656), ('inactive', 91979776), ('buffers', 50642944), ('cached', 223748096), ('shared', 851968), ('slab', 92323840)])
INFO:root:Wed Aug 26 11:10:50 2020 | cpu times: OrderedDict([('user', 261.03), ('nice', 32.8), ('system', 69.56), ('idle', 157532.21), ('iowait', 47.6), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.31), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 185888768), ('percent', 81.9), ('used', 681824256), ('free', 69926912), ('active', 724963328), ('inactive', 91979776), ('buffers', 50659328), ('cached', 223748096), ('shared', 851968), ('slab', 92348416)])
INFO:root:Wed Aug 26 11:11:50 2020 | cpu times: OrderedDict([('user', 261.91), ('nice', 32.8), ('system', 69.79), ('idle', 157590.99), ('iowait', 47.61), ('irq', 0.0), ('softirq', 1.31), ('steal', 21.32), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 182120448), ('percent', 82.3), ('used', 685854720), ('free', 97771520), ('active', 707477504), ('inactive', 81145856), ('buffers', 43794432), ('cached', 198737920), ('shared', 868352), ('slab', 91836416)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 11:12:51 2020 | Data from Google Sheet retrieved at Wed Aug 26 11:12:51 2020
INFO:root:Wed Aug 26 11:12:51 2020 | cpu times: OrderedDict([('user', 263.03), ('nice', 32.8), ('system', 70.17), ('idle', 157650.28), ('iowait', 47.62), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.33), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 161697792), ('percent', 84.2), ('used', 706236416), ('free', 77221888), ('active', 726315008), ('inactive', 80830464), ('buffers', 43814912), ('cached', 198885376), ('shared', 884736), ('slab', 92356608)])
INFO:root:Wed Aug 26 11:12:51 2020 | Beginning processing at Wed Aug 26 11:12:51 2020, running 1 queries
INFO:root:Wed Aug 26 11:12:51 2020 | cpu times: OrderedDict([('user', 263.04), ('nice', 32.8), ('system', 70.17), ('idle', 157650.28), ('iowait', 47.62), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.33), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 161439744), ('percent', 84.3), ('used', 706494464), ('free', 76963840), ('active', 726609920), ('inactive', 80830464), ('buffers', 43814912), ('cached', 198885376), ('shared', 884736), ('slab', 92356608)])
INFO:root:Wed Aug 26 11:13:06 2020 | Successful | 5 requests | Slack alert sent at Wed Aug 26 11:13:06 2020,
INFO:root:Wed Aug 26 11:13:06 2020 | Processing completed in 15.74 seconds
INFO:root:Wed Aug 26 11:13:06 2020 | cpu times: OrderedDict([('user', 263.18), ('nice', 32.8), ('system', 70.18), ('idle', 157665.84), ('iowait', 47.62), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.33), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 157663232), ('percent', 84.6), ('used', 710270976), ('free', 73179136), ('active', 730775552), ('inactive', 79548416), ('buffers', 43823104), ('cached', 198885376), ('shared', 884736), ('slab', 92446720)])
INFO:root:Wed Aug 26 11:14:07 2020 | cpu times: OrderedDict([('user', 264.64), ('nice', 32.8), ('system', 70.7), ('idle', 157723.78), ('iowait', 47.64), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.34), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 151932928), ('percent', 85.2), ('used', 716713984), ('free', 91344896), ('active', 728711168), ('inactive', 61919232), ('buffers', 37941248), ('cached', 180158464), ('shared', 909312), ('slab', 91594752)])
INFO:root:Wed Aug 26 11:15:07 2020 | cpu times: OrderedDict([('user', 264.79), ('nice', 32.8), ('system', 70.75), ('idle', 157783.53), ('iowait', 47.64), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.36), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 157655040), ('percent', 84.6), ('used', 710991872), ('free', 96919552), ('active', 725176320), ('inactive', 61902848), ('buffers', 37957632), ('cached', 180289536), ('shared', 909312), ('slab', 91430912)])
INFO:root:Wed Aug 26 11:16:07 2020 | cpu times: OrderedDict([('user', 264.81), ('nice', 32.8), ('system', 70.75), ('idle', 157843.42), ('iowait', 47.65), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.37), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 159330304), ('percent', 84.5), ('used', 709316608), ('free', 98557952), ('active', 724209664), ('inactive', 61898752), ('buffers', 37974016), ('cached', 180310016), ('shared', 909312), ('slab', 91422720)])
INFO:root:Wed Aug 26 11:17:07 2020 | cpu times: OrderedDict([('user', 264.85), ('nice', 32.8), ('system', 70.79), ('idle', 157903.28), ('iowait', 47.66), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.37), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 165785600), ('percent', 83.8), ('used', 702885888), ('free', 104919040), ('active', 720162816), ('inactive', 61861888), ('buffers', 37990400), ('cached', 180363264), ('shared', 876544), ('slab', 91181056)])
INFO:root:Wed Aug 26 11:18:07 2020 | cpu times: OrderedDict([('user', 264.86), ('nice', 32.8), ('system', 70.8), ('idle', 157963.2), ('iowait', 47.66), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.38), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 165552128), ('percent', 83.9), ('used', 703127552), ('free', 104660992), ('active', 720437248), ('inactive', 61865984), ('buffers', 37998592), ('cached', 180371456), ('shared', 876544), ('slab', 91181056)])
INFO:root:Wed Aug 26 11:19:07 2020 | cpu times: OrderedDict([('user', 264.88), ('nice', 32.8), ('system', 70.81), ('idle', 158023.07), ('iowait', 47.67), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.38), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 169590784), ('percent', 83.5), ('used', 699113472), ('free', 108560384), ('active', 717537280), ('inactive', 61980672), ('buffers', 38014976), ('cached', 180469760), ('shared', 860160), ('slab', 90992640)])
INFO:root:Wed Aug 26 11:20:07 2020 | cpu times: OrderedDict([('user', 264.92), ('nice', 32.8), ('system', 70.83), ('idle', 158082.97), ('iowait', 47.68), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.39), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 169824256), ('percent', 83.5), ('used', 698871808), ('free', 108785664), ('active', 717598720), ('inactive', 61980672), ('buffers', 38031360), ('cached', 180469760), ('shared', 860160), ('slab', 90992640)])
INFO:root:Wed Aug 26 11:21:07 2020 | cpu times: OrderedDict([('user', 264.94), ('nice', 32.8), ('system', 70.83), ('idle', 158142.89), ('iowait', 47.68), ('irq', 0.0), ('softirq', 1.32), ('steal', 21.39), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 169631744), ('percent', 83.5), ('used', 699072512), ('free', 108576768), ('active', 717881344), ('inactive', 61980672), ('buffers', 38039552), ('cached', 180469760), ('shared', 860160), ('slab', 90976256)])
INFO:root:Wed Aug 26 11:22:07 2020 | cpu times: OrderedDict([('user', 265.09), ('nice', 32.8), ('system', 70.95), ('idle', 158202.47), ('iowait', 47.75), ('irq', 0.0), ('softirq', 1.33), ('steal', 21.4), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 181841920), ('percent', 82.3), ('used', 686862336), ('free', 115159040), ('active', 718430208), ('inactive', 59273216), ('buffers', 38072320), ('cached', 186064896), ('shared', 860160), ('slab', 90247168)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 11:23:08 2020 | Data from Google Sheet retrieved at Wed Aug 26 11:23:08 2020
INFO:root:Wed Aug 26 11:23:08 2020 | cpu times: OrderedDict([('user', 269.88), ('nice', 32.8), ('system', 71.92), ('idle', 158256.56), ('iowait', 48.61), ('irq', 0.0), ('softirq', 1.38), ('steal', 21.44), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 72323072), ('percent', 93.0), ('used', 805507072), ('free', 70959104), ('active', 789381120), ('inactive', 38821888), ('buffers', 19120128), ('cached', 130572288), ('shared', 851968), ('slab', 80211968)])
INFO:root:Wed Aug 26 11:23:08 2020 | Beginning processing at Wed Aug 26 11:23:08 2020, running 2 queries
INFO:root:Wed Aug 26 11:23:08 2020 | cpu times: OrderedDict([('user', 269.9), ('nice', 32.8), ('system', 71.92), ('idle', 158256.56), ('iowait', 48.61), ('irq', 0.0), ('softirq', 1.38), ('steal', 21.44), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 70516736), ('percent', 93.1), ('used', 806817792), ('free', 68636672), ('active', 791187456), ('inactive', 39337984), ('buffers', 19120128), ('cached', 131584000), ('shared', 851968), ('slab', 80211968)])
INFO:root:Wed Aug 26 11:56:37 2020 | Data from Google Sheet retrieved at Wed Aug 26 11:56:37 2020
INFO:root:Wed Aug 26 11:56:37 2020 | cpu times: OrderedDict([('user', 282.77), ('nice', 32.8), ('system', 1770.7), ('idle', 158505.7), ('iowait', 83.12), ('irq', 0.0), ('softirq', 11.35), ('steal', 22.5), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 296382464), ('percent', 71.1), ('used', 580911104), ('free', 158203904), ('active', 585216000), ('inactive', 167911424), ('buffers', 29675520), ('cached', 257368064), ('shared', 802816), ('slab', 72749056)])
INFO:root:Wed Aug 26 11:56:37 2020 | Beginning processing at Wed Aug 26 11:56:37 2020, running 2 queries
INFO:root:Wed Aug 26 11:56:37 2020 | cpu times: OrderedDict([('user', 282.78), ('nice', 32.8), ('system', 1770.7), ('idle', 158505.7), ('iowait', 83.12), ('irq', 0.0), ('softirq', 11.35), ('steal', 22.5), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 296677376), ('percent', 71.1), ('used', 580644864), ('free', 158203904), ('active', 585621504), ('inactive', 168206336), ('buffers', 29675520), ('cached', 257634304), ('shared', 802816), ('slab', 72749056)])
INFO:root:Wed Aug 26 11:56:51 2020 | Error | query returned 0 results
INFO:root:Wed Aug 26 11:57:07 2020 | Successful | 3 requests | Slack alert sent at Wed Aug 26 11:57:07 2020,
INFO:root:Wed Aug 26 11:57:08 2020 | Processing completed in 31.03 seconds
INFO:root:Wed Aug 26 11:57:08 2020 | cpu times: OrderedDict([('user', 283.17), ('nice', 32.8), ('system', 1770.76), ('idle', 158535.82), ('iowait', 83.46), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.52), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 283750400), ('percent', 72.3), ('used', 592789504), ('free', 138272768), ('active', 601382912), ('inactive', 171253760), ('buffers', 32227328), ('cached', 262868992), ('shared', 802816), ('slab', 74412032)])
INFO:root:Wed Aug 26 11:58:08 2020 | cpu times: OrderedDict([('user', 283.26), ('nice', 32.8), ('system', 1770.79), ('idle', 158595.61), ('iowait', 83.46), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.52), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 282210304), ('percent', 72.5), ('used', 594329600), ('free', 136724480), ('active', 602075136), ('inactive', 171253760), ('buffers', 32235520), ('cached', 262868992), ('shared', 802816), ('slab', 74412032)])
INFO:root:Wed Aug 26 11:59:08 2020 | cpu times: OrderedDict([('user', 283.37), ('nice', 32.8), ('system', 1770.85), ('idle', 158655.37), ('iowait', 83.47), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.53), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 280670208), ('percent', 72.6), ('used', 595861504), ('free', 135176192), ('active', 603770880), ('inactive', 171253760), ('buffers', 32251904), ('cached', 262868992), ('shared', 802816), ('slab', 74412032)])
INFO:root:Wed Aug 26 12:00:08 2020 | cpu times: OrderedDict([('user', 283.45), ('nice', 32.8), ('system', 1770.87), ('idle', 158715.15), ('iowait', 83.47), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.62), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 280256512), ('percent', 72.7), ('used', 596365312), ('free', 134660096), ('active', 604065792), ('inactive', 171339776), ('buffers', 32260096), ('cached', 262873088), ('shared', 802816), ('slab', 74412032)])
INFO:root:Wed Aug 26 12:01:08 2020 | cpu times: OrderedDict([('user', 283.57), ('nice', 32.8), ('system', 1770.93), ('idle', 158774.78), ('iowait', 83.48), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.64), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 555335680), ('percent', 45.9), ('used', 321286144), ('free', 409608192), ('active', 341938176), ('inactive', 161804288), ('buffers', 32276480), ('cached', 262987776), ('shared', 802816), ('slab', 74043392)])
INFO:root:Wed Aug 26 12:02:08 2020 | cpu times: OrderedDict([('user', 283.6), ('nice', 32.8), ('system', 1770.94), ('idle', 158834.7), ('iowait', 83.49), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.65), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 555118592), ('percent', 45.9), ('used', 321495040), ('free', 409382912), ('active', 342347776), ('inactive', 161779712), ('buffers', 32292864), ('cached', 262987776), ('shared', 802816), ('slab', 74043392)])
INFO:root:Wed Aug 26 12:03:08 2020 | cpu times: OrderedDict([('user', 283.63), ('nice', 32.8), ('system', 1770.94), ('idle', 158894.64), ('iowait', 83.49), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.65), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 555958272), ('percent', 45.8), ('used', 320663552), ('free', 410206208), ('active', 341626880), ('inactive', 161779712), ('buffers', 32301056), ('cached', 262987776), ('shared', 802816), ('slab', 74043392)])
INFO:root:Wed Aug 26 12:04:08 2020 | cpu times: OrderedDict([('user', 283.66), ('nice', 32.8), ('system', 1770.95), ('idle', 158954.55), ('iowait', 83.5), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.66), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 557039616), ('percent', 45.7), ('used', 319582208), ('free', 411271168), ('active', 340512768), ('inactive', 161779712), ('buffers', 32317440), ('cached', 262987776), ('shared', 802816), ('slab', 74043392)])
INFO:root:Wed Aug 26 12:05:08 2020 | cpu times: OrderedDict([('user', 283.69), ('nice', 32.8), ('system', 1770.97), ('idle', 159014.41), ('iowait', 83.5), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.66), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 554172416), ('percent', 46.0), ('used', 322449408), ('free', 408395776), ('active', 343207936), ('inactive', 161779712), ('buffers', 32325632), ('cached', 262987776), ('shared', 802816), ('slab', 74133504)])
INFO:root:Wed Aug 26 12:06:08 2020 | cpu times: OrderedDict([('user', 283.71), ('nice', 32.8), ('system', 1770.98), ('idle', 159074.3), ('iowait', 83.51), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.67), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 554291200), ('percent', 46.0), ('used', 322330624), ('free', 408477696), ('active', 342646784), ('inactive', 161763328), ('buffers', 32358400), ('cached', 262991872), ('shared', 802816), ('slab', 74137600)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 12:07:09 2020 | Data from Google Sheet retrieved at Wed Aug 26 12:07:09 2020
INFO:root:Wed Aug 26 12:07:09 2020 | cpu times: OrderedDict([('user', 283.87), ('nice', 32.8), ('system', 1771.01), ('idle', 159135.12), ('iowait', 83.51), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.67), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 543043584), ('percent', 47.1), ('used', 333565952), ('free', 397189120), ('active', 355409920), ('inactive', 161767424), ('buffers', 32374784), ('cached', 263028736), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:07:09 2020 | Beginning processing at Wed Aug 26 12:07:09 2020, running 2 queries
INFO:root:Wed Aug 26 12:07:09 2020 | cpu times: OrderedDict([('user', 283.88), ('nice', 32.8), ('system', 1771.01), ('idle', 159135.12), ('iowait', 83.51), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.67), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 543043584), ('percent', 47.1), ('used', 333565952), ('free', 397189120), ('active', 355409920), ('inactive', 161767424), ('buffers', 32374784), ('cached', 263028736), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:08:03 2020 | Successful | No alert triggered
INFO:root:Wed Aug 26 12:08:30 2020 | Successful | No alert triggered
INFO:root:Wed Aug 26 12:08:30 2020 | Processing completed in 80.85 seconds
INFO:root:Wed Aug 26 12:08:30 2020 | cpu times: OrderedDict([('user', 284.25), ('nice', 32.8), ('system', 1771.05), ('idle', 159215.43), ('iowait', 83.52), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.68), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 535576576), ('percent', 47.8), ('used', 341032960), ('free', 389705728), ('active', 362758144), ('inactive', 161767424), ('buffers', 32391168), ('cached', 263028736), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:09:30 2020 | cpu times: OrderedDict([('user', 284.27), ('nice', 32.8), ('system', 1771.06), ('idle', 159275.32), ('iowait', 83.52), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.69), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 536403968), ('percent', 47.7), ('used', 340197376), ('free', 390520832), ('active', 361107456), ('inactive', 161771520), ('buffers', 32407552), ('cached', 263032832), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:10:30 2020 | cpu times: OrderedDict([('user', 284.28), ('nice', 32.8), ('system', 1771.07), ('idle', 159335.26), ('iowait', 83.53), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.69), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 536420352), ('percent', 47.7), ('used', 340189184), ('free', 390520832), ('active', 361226240), ('inactive', 161771520), ('buffers', 32415744), ('cached', 263032832), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:11:30 2020 | cpu times: OrderedDict([('user', 284.3), ('nice', 32.8), ('system', 1771.08), ('idle', 159395.19), ('iowait', 83.53), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.7), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 536440832), ('percent', 47.7), ('used', 340168704), ('free', 390520832), ('active', 362151936), ('inactive', 161775616), ('buffers', 32432128), ('cached', 263036928), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:12:30 2020 | cpu times: OrderedDict([('user', 284.32), ('nice', 32.8), ('system', 1771.09), ('idle', 159455.12), ('iowait', 83.54), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.7), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 535674880), ('percent', 47.8), ('used', 340934656), ('free', 389746688), ('active', 362221568), ('inactive', 161775616), ('buffers', 32440320), ('cached', 263036928), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:13:30 2020 | cpu times: OrderedDict([('user', 284.34), ('nice', 32.8), ('system', 1771.11), ('idle', 159515.04), ('iowait', 83.55), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.71), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 535142400), ('percent', 47.8), ('used', 341467136), ('free', 389197824), ('active', 362364928), ('inactive', 161771520), ('buffers', 32456704), ('cached', 263036928), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:14:30 2020 | cpu times: OrderedDict([('user', 284.35), ('nice', 32.8), ('system', 1771.12), ('idle', 159574.98), ('iowait', 83.55), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.72), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 535412736), ('percent', 47.8), ('used', 341196800), ('free', 389455872), ('active', 362483712), ('inactive', 161775616), ('buffers', 32464896), ('cached', 263041024), ('shared', 802816), ('slab', 74158080)])
INFO:root:Wed Aug 26 12:15:30 2020 | cpu times: OrderedDict([('user', 284.39), ('nice', 32.8), ('system', 1771.12), ('idle', 159634.92), ('iowait', 83.55), ('irq', 0.0), ('softirq', 11.36), ('steal', 22.72), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 534917120), ('percent', 47.9), ('used', 341692416), ('free', 388939776), ('active', 362655744), ('inactive', 161775616), ('buffers', 32481280), ('cached', 263045120), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:16:31 2020 | cpu times: OrderedDict([('user', 284.41), ('nice', 32.8), ('system', 1771.12), ('idle', 159694.83), ('iowait', 83.56), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.73), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 536698880), ('percent', 47.7), ('used', 339910656), ('free', 390713344), ('active', 361086976), ('inactive', 161775616), ('buffers', 32489472), ('cached', 263045120), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:17:31 2020 | cpu times: OrderedDict([('user', 284.44), ('nice', 32.8), ('system', 1771.13), ('idle', 159754.74), ('iowait', 83.56), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.73), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 536522752), ('percent', 47.7), ('used', 340082688), ('free', 390488064), ('active', 361242624), ('inactive', 161796096), ('buffers', 32509952), ('cached', 263077888), ('shared', 802816), ('slab', 74162176)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 12:18:32 2020 | Data from Google Sheet retrieved at Wed Aug 26 12:18:32 2020
INFO:root:Wed Aug 26 12:18:32 2020 | cpu times: OrderedDict([('user', 284.56), ('nice', 32.8), ('system', 1771.15), ('idle', 159815.67), ('iowait', 83.57), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.74), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 525447168), ('percent', 48.8), ('used', 351158272), ('free', 379392000), ('active', 373248000), ('inactive', 161796096), ('buffers', 32526336), ('cached', 263081984), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:18:32 2020 | Beginning processing at Wed Aug 26 12:18:32 2020, running 2 queries
INFO:root:Wed Aug 26 12:18:32 2020 | cpu times: OrderedDict([('user', 284.56), ('nice', 32.8), ('system', 1771.15), ('idle', 159815.67), ('iowait', 83.57), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.74), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 525447168), ('percent', 48.8), ('used', 351158272), ('free', 379392000), ('active', 373248000), ('inactive', 161796096), ('buffers', 32526336), ('cached', 263081984), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:18:54 2020 | Successful | No alert triggered
INFO:root:Wed Aug 26 12:19:12 2020 | Successful | No alert triggered
INFO:root:Wed Aug 26 12:19:12 2020 | Processing completed in 40.10 seconds
INFO:root:Wed Aug 26 12:19:12 2020 | cpu times: OrderedDict([('user', 284.8), ('nice', 32.8), ('system', 1771.17), ('idle', 159855.45), ('iowait', 83.57), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.74), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 519520256), ('percent', 49.4), ('used', 357085184), ('free', 373456896), ('active', 378597376), ('inactive', 161796096), ('buffers', 32534528), ('cached', 263081984), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:20:12 2020 | cpu times: OrderedDict([('user', 284.81), ('nice', 32.8), ('system', 1771.18), ('idle', 159915.35), ('iowait', 83.58), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.75), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 518680576), ('percent', 49.5), ('used', 357924864), ('free', 372600832), ('active', 379592704), ('inactive', 161796096), ('buffers', 32550912), ('cached', 263081984), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:21:12 2020 | cpu times: OrderedDict([('user', 284.83), ('nice', 32.8), ('system', 1771.19), ('idle', 159975.23), ('iowait', 83.58), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.76), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 517398528), ('percent', 49.6), ('used', 359206912), ('free', 371310592), ('active', 379736064), ('inactive', 161779712), ('buffers', 32559104), ('cached', 263081984), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:22:12 2020 | cpu times: OrderedDict([('user', 284.86), ('nice', 32.8), ('system', 1771.2), ('idle', 160035.13), ('iowait', 83.59), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.76), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 518758400), ('percent', 49.4), ('used', 357847040), ('free', 372649984), ('active', 378847232), ('inactive', 161783808), ('buffers', 32575488), ('cached', 263086080), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:23:12 2020 | cpu times: OrderedDict([('user', 284.87), ('nice', 32.8), ('system', 1771.2), ('idle', 160095.05), ('iowait', 83.59), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.77), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 519057408), ('percent', 49.4), ('used', 357539840), ('free', 372940800), ('active', 378957824), ('inactive', 161783808), ('buffers', 32591872), ('cached', 263086080), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:24:12 2020 | cpu times: OrderedDict([('user', 284.88), ('nice', 32.8), ('system', 1771.21), ('idle', 160154.94), ('iowait', 83.6), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.77), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 517971968), ('percent', 49.5), ('used', 358633472), ('free', 371834880), ('active', 379842560), ('inactive', 161787904), ('buffers', 32600064), ('cached', 263090176), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:25:12 2020 | cpu times: OrderedDict([('user', 284.89), ('nice', 32.8), ('system', 1771.22), ('idle', 160214.82), ('iowait', 83.6), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.78), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 517980160), ('percent', 49.5), ('used', 358617088), ('free', 371834880), ('active', 379965440), ('inactive', 161787904), ('buffers', 32616448), ('cached', 263090176), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:26:12 2020 | cpu times: OrderedDict([('user', 284.91), ('nice', 32.8), ('system', 1771.22), ('idle', 160274.71), ('iowait', 83.61), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.78), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 518553600), ('percent', 49.5), ('used', 358051840), ('free', 372391936), ('active', 379281408), ('inactive', 161787904), ('buffers', 32624640), ('cached', 263090176), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:27:12 2020 | cpu times: OrderedDict([('user', 284.93), ('nice', 32.8), ('system', 1771.23), ('idle', 160334.59), ('iowait', 83.61), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.79), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 517189632), ('percent', 49.6), ('used', 359407616), ('free', 371019776), ('active', 380162048), ('inactive', 161787904), ('buffers', 32641024), ('cached', 263090176), ('shared', 802816), ('slab', 74162176)])
INFO:root:Wed Aug 26 12:28:12 2020 | cpu times: OrderedDict([('user', 284.95), ('nice', 32.8), ('system', 1771.24), ('idle', 160394.48), ('iowait', 83.62), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.79), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 516694016), ('percent', 49.6), ('used', 359911424), ('free', 370503680), ('active', 380862464), ('inactive', 161787904), ('buffers', 32649216), ('cached', 263094272), ('shared', 802816), ('slab', 74166272)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 12:29:13 2020 | Data from Google Sheet retrieved at Wed Aug 26 12:29:13 2020
INFO:root:Wed Aug 26 12:29:13 2020 | cpu times: OrderedDict([('user', 285.07), ('nice', 32.8), ('system', 1771.26), ('idle', 160455.38), ('iowait', 83.62), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.8), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 503115776), ('percent', 51.0), ('used', 373481472), ('free', 356909056), ('active', 395579392), ('inactive', 161787904), ('buffers', 32665600), ('cached', 263102464), ('shared', 802816), ('slab', 74170368)])
INFO:root:Wed Aug 26 12:29:13 2020 | Beginning processing at Wed Aug 26 12:29:13 2020, running 2 queries
INFO:root:Wed Aug 26 12:29:13 2020 | cpu times: OrderedDict([('user', 285.07), ('nice', 32.8), ('system', 1771.26), ('idle', 160455.38), ('iowait', 83.62), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.8), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 503115776), ('percent', 51.0), ('used', 373481472), ('free', 356909056), ('active', 395579392), ('inactive', 161787904), ('buffers', 32665600), ('cached', 263102464), ('shared', 802816), ('slab', 74170368)])
INFO:root:Wed Aug 26 12:29:27 2020 | Successful | No alert triggered
INFO:root:Wed Aug 26 12:29:43 2020 | Successful | 2 requests | Slack alert sent at Wed Aug 26 12:29:43 2020,
INFO:root:Wed Aug 26 12:29:43 2020 | Processing completed in 29.90 seconds
INFO:root:Wed Aug 26 12:29:43 2020 | cpu times: OrderedDict([('user', 285.3), ('nice', 32.8), ('system', 1771.29), ('idle', 160484.98), ('iowait', 83.63), ('irq', 0.0), ('softirq', 11.37), ('steal', 22.8), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 498225152), ('percent', 51.4), ('used', 378376192), ('free', 352006144), ('active', 400166912), ('inactive', 161792000), ('buffers', 32673792), ('cached', 263102464), ('shared', 802816), ('slab', 74170368)])
INFO:root:Wed Aug 26 12:30:43 2020 | cpu times: OrderedDict([('user', 285.77), ('nice', 32.8), ('system', 1771.5), ('idle', 160544.0), ('iowait', 83.79), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.86), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 494551040), ('percent', 51.8), ('used', 381652992), ('free', 342511616), ('active', 406605824), ('inactive', 162684928), ('buffers', 33640448), ('cached', 268353536), ('shared', 811008), ('slab', 74952704)])
INFO:root:Wed Aug 26 12:31:43 2020 | cpu times: OrderedDict([('user', 285.79), ('nice', 32.8), ('system', 1771.5), ('idle', 160603.89), ('iowait', 83.79), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.87), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495824896), ('percent', 51.7), ('used', 380379136), ('free', 343769088), ('active', 405721088), ('inactive', 162684928), ('buffers', 33656832), ('cached', 268353536), ('shared', 811008), ('slab', 74952704)])
INFO:root:Wed Aug 26 12:32:43 2020 | cpu times: OrderedDict([('user', 285.82), ('nice', 32.8), ('system', 1771.52), ('idle', 160663.76), ('iowait', 83.8), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.87), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 496214016), ('percent', 51.6), ('used', 379990016), ('free', 343515136), ('active', 405819392), ('inactive', 163323904), ('buffers', 33665024), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:33:43 2020 | cpu times: OrderedDict([('user', 285.83), ('nice', 32.8), ('system', 1771.53), ('idle', 160723.66), ('iowait', 83.81), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.88), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495714304), ('percent', 51.7), ('used', 380489728), ('free', 342999040), ('active', 405909504), ('inactive', 163323904), ('buffers', 33681408), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:34:43 2020 | cpu times: OrderedDict([('user', 285.84), ('nice', 32.8), ('system', 1771.54), ('idle', 160783.56), ('iowait', 83.81), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.88), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495464448), ('percent', 51.7), ('used', 380739584), ('free', 342740992), ('active', 405995520), ('inactive', 163323904), ('buffers', 33689600), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:35:43 2020 | cpu times: OrderedDict([('user', 285.85), ('nice', 32.8), ('system', 1771.54), ('idle', 160843.47), ('iowait', 83.82), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.89), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495480832), ('percent', 51.7), ('used', 380723200), ('free', 342740992), ('active', 406077440), ('inactive', 163323904), ('buffers', 33705984), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:36:43 2020 | cpu times: OrderedDict([('user', 285.85), ('nice', 32.8), ('system', 1771.54), ('idle', 160903.37), ('iowait', 83.82), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.89), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495489024), ('percent', 51.7), ('used', 380715008), ('free', 342740992), ('active', 406163456), ('inactive', 163323904), ('buffers', 33714176), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:37:43 2020 | cpu times: OrderedDict([('user', 285.86), ('nice', 32.8), ('system', 1771.56), ('idle', 160963.27), ('iowait', 83.83), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.9), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495247360), ('percent', 51.7), ('used', 380956672), ('free', 342482944), ('active', 406278144), ('inactive', 163323904), ('buffers', 33730560), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
INFO:root:Wed Aug 26 12:38:43 2020 | cpu times: OrderedDict([('user', 285.88), ('nice', 32.8), ('system', 1771.57), ('idle', 161023.18), ('iowait', 83.83), ('irq', 0.0), ('softirq', 11.38), ('steal', 22.9), ('guest', 0.0), ('guest_nice', 0.0)]) | virtual memory: OrderedDict([('total', 1026158592), ('available', 495255552), ('percent', 51.7), ('used', 380948480), ('free', 342482944), ('active', 406368256), ('inactive', 163323904), ('buffers', 33738752), ('cached', 268988416), ('shared', 811008), ('slab', 74985472)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 12:39:43 2020 | Error Unable to find the server at www.googleapis.com, waiting 5 minutes
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/share/virtualenvs/ams-alert-monitoring-DDDj364Y/lib/python3.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
INFO:root:Wed Aug 26 12:45:43 2020 | Error Unable to find the server at www.googleapis.com, waiting 5 minutes
INFO:root:Wed Aug 26 12:51:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 12:57:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef758550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:03:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6e9290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:09:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef758b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:15:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75db10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:21:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef71ced0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:27:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:33:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:39:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:45:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef71ca90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:51:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d2d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 13:57:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710bd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:03:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:09:44 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75db50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:15:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:21:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:27:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:33:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:39:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:45:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4f090c1d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:51:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 14:57:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:03:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef9c6d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:09:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75df50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:15:45 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:21:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:27:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7171d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:33:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717dd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:39:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:45:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:51:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef741fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 15:57:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fbb90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:03:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:09:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:15:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:21:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:27:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:33:46 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:39:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef704ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:45:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:51:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef977310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 16:57:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:03:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:09:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7043d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:15:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:21:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7101d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:27:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fbb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:33:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:39:47 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7044d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:45:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fbad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:51:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 17:57:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef977690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:03:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:09:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6e41d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:15:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:21:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:27:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:33:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:39:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6e4ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:45:48 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fba10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:51:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7105d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 18:57:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef704410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:03:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75d990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:09:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6e1c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:15:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef977310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:21:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:27:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fbb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:33:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:39:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6de950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:45:49 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:51:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 19:57:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7045d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:03:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef75dcd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:09:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6a2690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:15:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6debd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:21:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:27:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:33:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:39:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fb450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:45:50 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:51:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 20:57:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6de890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:03:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef9c6f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:09:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef704290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:15:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef9c6e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:21:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6de790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:27:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:33:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:39:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef704150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:45:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:51:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 21:57:51 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6dea10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:03:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef741d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:09:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef704090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:15:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6fbdd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:21:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef6de390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:27:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:33:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef74e090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:39:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef7041d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:45:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef717a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
INFO:root:Wed Aug 26 22:51:52 2020 | Error HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4ef710e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')), waiting 5 minutes
